71 user prompts [wip]
LangCorrect/server pull request #122
Opened 2023-09-24 04:21 UTC by keyxcode

2023-09-24 05:31 UTC, keyxcode commented
Hi @danielzeljko, there are a few things in this PR that I'd like to note:
- I've added the `translate` tag but it didn't seem to translate anything except the "Created" header when I tried a few different languages.
- I thought about the situation you mentioned when a user turns off JS and decided to make the prompt an `a` in addition to the row being clickable - that way we offer both good UX and a fail-safe option. That led me to discover that in Bootstrap 5.3 there's a lot of added support for styling links e.g. disabling the underline. Is this something you plan on doing?

2023-09-24 20:51 UTC, danielzeljko commented
Hi @keyxcode,

> I've added the translate tag but it didn't seem to translate anything except the "Created" header when I tried a few different languages.

When using the Django translate tag, only those strings that have corresponding translations will be converted to the selected language. If a translation is not available for a specific string, Django will default back to the original string. So in your case. the created header is the only string that's changing because that's the only string that is translated. 

Once #38 is merged all of those strings should have translations.

> Is this something you plan on doing?

Hmm, I'm not quite sure I follow. Those BS styling features are implemented as classes, so we can already use them to style elements as needed. Please let me know if we're thinking about two different things.

2023-09-25 12:36 UTC, keyxcode commented
Here's what I mean: currently I'm using Bootstrap's`link-dark` to style the prompt's content; however, that leaves underlines that I'd rather not have. In the version of BS we're using (5.2.3), there's no native way to get rid of them afaik, but in the newest version 5.3, there is: https://getbootstrap.com/docs/5.3/utilities/link/ 

Therefore I wonder if I should update to BS 5.3 to use this feature. If you think that this update is non-trivial and should be left for later then I'll just write some custom CSS to remove the underlines.

Hope that was clearer!

2023-09-25 21:57 UTC, danielzeljko commented
It's a bit hidden in the documentation, but there's already a way to remove the underline for anchor tags by applying the `text-decoration-none` class, see https://getbootstrap.com/docs/5.2/utilities/text/#text-decoration. This will also work on BS v5.3.

It would be great to update BS, but we should do this as a separate issue as there may be some breaking changes.

2023-09-26 06:44 UTC, keyxcode commented
Thanks for the tip @danielzeljko Idk why my google searches have only pointed me to v5.3 and not that. I have updated the PR and it's ready for reviews.

2023-09-29 22:30 UTC, danielzeljko requested changes
Nice work Cadence! Let's get these small changes in and it'll be ready for merging 🥳

2023-09-29 22:30 UTC, danielzeljko commented on langcorrect/static/js/user_prompts.js
> +window.addEventListener("DOMContentLoaded", () => {
As a best practice, always add the `use strict` directive at the top of your `.js` files. This will help deal with JS quirkiness by catching common errors and preventing certain unsafe actions. You can learn more by checking out https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode.

2023-09-29 22:30 UTC, danielzeljko commented on langcorrect/static/js/user_prompts.js
> +        window.location = link;
Before navigating, we should add a check to ensure that `row.dataset.link` exists:

    if (link) { ... }

2023-09-29 22:30 UTC, danielzeljko commented on langcorrect/templates/prompts/user_prompts.html
> +            <td>{{ prompt.language }}</td>
Let's change this to use the language shortcode instead. See: https://github.com/LangCorrect/server/pull/123#discussion_r1341807224

2023-09-29 22:30 UTC, danielzeljko commented on langcorrect/templates/prompts/user_prompts.html
> +  </div>
Don't forget to include pagination:

    {% include "pagination.html" %}

2023-09-29 22:30 UTC, danielzeljko commented on langcorrect/templates/prompts/user_prompts.html
> +            <th scope="row">{{ forloop.counter }}</th>
@chrisjoel10 brought up a great observation that we were resetting the counter on every page. See https://github.com/LangCorrect/server/pull/123#discussion_r1336389161 for fix.

2023-09-29 22:30 UTC, danielzeljko commented on langcorrect/templates/prompts/user_prompts.html
> +  {% translate "Prompts" %} · LangCorrect
Let's change this to say My Prompts

2023-09-29 22:30 UTC, danielzeljko commented on langcorrect/prompts/urls.py
> +    path("me", view=user_prompts_view, name="user_prompts"),
See https://github.com/LangCorrect/server/pull/123#discussion_r1341785514

2023-10-01 01:51 UTC, keyxcode commented on langcorrect/prompts/urls.py
> +    path("me", view=user_prompts_view, name="user_prompts"),
Oh shoot this was an early experiment that I forgot to leave out! Thanks for having found it!

2023-10-01 20:01 UTC, danielzeljko approved these changes
Looks good to me!

2023-10-01 20:02 UTC, merged