Create a Page to Display User-Submitted Posts(#72)
LangCorrect/server pull request #123
Opened 2023-09-24 22:45 UTC by ChrisJoel10

2023-09-24 22:53 UTC, chrismathew047 commented
closes #72

* Creates a new route: /submissions/posts
* List all journal entries submitted by the current user
* Provides options to view, edit, or delete each journal entry

Screenshot:
![image](https://github.com/LangCorrect/server/assets/115909094/7f943c7d-5d5f-4820-a312-11d784659573)

2023-09-25 21:35 UTC, danielzeljko requested changes

2023-09-25 21:35 UTC, danielzeljko commented on langcorrect/templates/submissions/post_list.html
> +            <td>{{ forloop.counter|add:page_obj.start_index|add:-1 }}</td>
Let's simplify this to `{{ page_obj.start_index|add:forloop.counter0 }}`

2023-09-25 21:35 UTC, danielzeljko commented on config/settings/base.py
> +    "langcorrect.submissions",
Since the submission feature is essentially just a view of posts filtered by the current user, I feel that having a separate app might be a bit overkill in this case. I'm leaning more towards renaming your view to `UserSubmittedPosts` and moving it to the posts app. As for the URLs, we can just directly add them under the root URLs.

@keyxcode is also working on a similar task #71 to display user-submitted prompts. I'd love to hear both of your thoughts on this approach.

2023-09-25 21:35 UTC, danielzeljko commented on langcorrect/templates/submissions/post_list.html
> +              {% if post.iscorrected == 1 %}
There's a small typo here -- it should be `is_corrected`

2023-09-26 06:56 UTC, keyxcode commented on config/settings/base.py
> +    "langcorrect.submissions",
> @keyxcode is also working on a similar task #71 to display user-submitted prompts. I'd love to hear both of your thoughts on this approach.

At first I thought of doing the exact the same thing as you @chrismathew047 (creating a submissions app) but it does seem a bit overkill because we're just reusing pieces from the Posts and Prompts app instead of creating some new Submissions entity.

2023-09-26 10:22 UTC, chrismathew047 commented on config/settings/base.py
> +    "langcorrect.submissions",
Thanks @danielzeljko and @keyxcode! I totally agree, this does seem like an overkill to me now. It makes a lot of sense to move the view to the posts app instead of having a new app. Thanks once again for the suggestions!

2023-09-28 21:27 UTC, chrismathew047 approved these changes

2023-09-28 22:05 UTC, chrismathew047 commented
Thanks for the suggestions @danielzeljko. I have updated the pr and it is read for review

2023-09-29 21:30 UTC, danielzeljko requested changes
Nice work Chris! We just need to make a few small changes, and it'll be ready to merge into main🥳

2023-09-29 21:30 UTC, danielzeljko commented on langcorrect/templates/posts/user_posts.html
> +            <td>{{ post.created }}</td>
We should change this to use the [naturalday](https://docs.djangoproject.com/en/4.2/ref/contrib/humanize/#naturalday) template tag:

    <td>{{ post.created|naturalday }}</td>

By doing so, we can make the dates more human-readable and enable automatic translation into different locales.

2023-09-29 21:30 UTC, danielzeljko commented on langcorrect/templates/posts/user_posts.html
> +              {% for tag in post.tags.names %}<span class="badge bg-secondary">{{ tag }}</span>{% endfor %}
We should introduce some small margins to the end of each badge so that they have some room to breathe and improve the visual separation between them. What does it look like with `me-1`?

2023-09-29 21:30 UTC, danielzeljko commented on langcorrect/templates/posts/user_posts.html
> +            <td>{{ post.language }}</td>
On second thought, let's use the language shortcode to display the language information. This will help conserve horizontal space in the table and make the UI more compact. Additionally, I'm not sure what the max width would be if the language is translated into different languages, so using this approach would be more reliable.

    <td>{{ post.language.code }}</td>

2023-10-01 01:43 UTC, ChrisJoel10 commented on langcorrect/posts/urls.py
> +    path("me", view=user_posts_view, name="user_posts"),
Oh. Got it👍

2023-10-01 01:46 UTC, ChrisJoel10 commented on langcorrect/templates/posts/user_posts.html
> +              {% for tag in post.tags.names %}<span class="badge bg-secondary">{{ tag }}</span>{% endfor %}
![image](https://github.com/LangCorrect/server/assets/119527459/b0f0c631-473b-4d28-a739-bf5a09ec8643)

It looks good to me with `me-1`. What do you think?

2023-10-01 01:50 UTC, ChrisJoel10 commented
I have updated the code. Looking forward to hear your feedback @danielzeljko. Thanks once again for the suggestions!

2023-10-01 20:18 UTC, danielzeljko requested changes
![image](https://github.com/LangCorrect/server/assets/115326106/3a9f3b39-b135-4872-b168-76fd8a6a34e0)

Let's update this nav item so that it'll take the user to the right page. Other than that, it looks great!

2023-10-01 20:50 UTC, danielzeljko approved these changes
Looks good to me!

2023-10-01 20:52 UTC, merged