Verify emails automatically (#12)
LangCorrect/server pull request #143
Opened 2023-10-05 18:53 UTC by keyxcode

closes #12 

Please let me know if you have any comments @danielzeljko

2023-10-07 22:10 UTC, danielzeljko requested changes
Nice work with the script! My review is mostly some performance enhancements and some things to keep in mind.

2023-10-07 22:10 UTC, danielzeljko commented on langcorrect/users/management/commands/verify_emails.py
> +                    print(e)
I would use `logger.error` here because it will not only capture the error, but automatically send the event details to Sentry for monitoring.

Something like:

    logger.error(f"Failed to verify email {email.email}: {e}")
    
I would also consider renaming your email variable to email_address for better readability:

`email.email` vs `email_address.email`

2023-10-08 03:27 UTC, keyxcode commented on langcorrect/users/management/commands/verify_emails.py
> +            verified_user_emails = user.emailaddress_set.all()
That's a good point. What I had in mind was "`emails` that belong to the `verified_user`", but clearly it can cause some confusion.

2023-10-08 03:32 UTC, keyxcode commented on langcorrect/users/management/commands/verify_emails.py
> +                if email.verified:
The reason I did this is because I usually try to avoid extra indentation whenever possible. But in this case, I do think your version is more readable and there's not too much indentation to worry about.

2023-10-08 04:22 UTC, keyxcode commented on langcorrect/users/management/commands/verify_emails.py
> +        verified_users = User.objects.filter(is_verified=True)
That's a great advice and a new topic for me to delve into. Thanks!

2023-10-09 07:06 UTC, danielzeljko approved these changes

2023-10-09 07:06 UTC, merged