Verify emails automatically (update) (#12)
LangCorrect/server pull request #180
Opened 2023-10-10 14:33 UTC by keyxcode

closes #12 

I believe I've addressed the issue you were talking about @danielzeljko Please let me know if you have any comments

2023-10-11 00:30 UTC, danielzeljko requested changes
I think it'll all be set and ready to merge afterward.

2023-10-11 00:30 UTC, danielzeljko commented on langcorrect/users/management/commands/verify_emails.py
> +                EmailAddress.objects.create(user=user, email=user.email, verified=True)
In this case, the email is considered a `primary` email. Let's make sure to include this.

2023-10-11 00:30 UTC, danielzeljko commented on langcorrect/users/management/commands/verify_emails.py
> +            for email_address in user.emailaddress_set.all():
We need to update this entire block so that only the primary email is set to `verified=True`. What's happening now is that all of that user's emails are set to True including unverified ones.

For example:
- dan@dundermifflin.com <--- previously verified
- dantheman@dundermifflin.com <--- not verified
- jibberishnotmyrealemail@dundermifflin.com <--- not verified

We only want to make sure to set the emails that were previously verified to true.

2023-10-11 18:16 UTC, keyxcode commented on langcorrect/users/management/commands/verify_emails.py
> +            for email_address in user.emailaddress_set.all():
Is this what you mean? `for email_address in user.emailaddress_set.filter(primary=True):`
I might need to ask you for a quick call when you have time to better understand the task

2023-10-11 21:48 UTC, danielzeljko commented on langcorrect/users/management/commands/verify_emails.py
> +            for email_address in user.emailaddress_set.all():
Not quite -- let's hop on a call. Can you DM me on discord with your availability. We'll go through the entire flow together 🙌

2023-10-13 13:48 UTC, keyxcode commented
Please review the new command @danielzeljko
Please note that I have changed the command name to `migrate_verified_emails` - I thought that it reflected the command's purpose better.

2023-10-15 01:45 UTC, danielzeljko approved these changes
Nice work 🎉

2023-10-15 01:46 UTC, merged