Profile page improvements (#183)
LangCorrect/server pull request #184
Opened 2023-10-10 18:53 UTC by keyxcode

closes #183 

<img width="1286" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/762987e2-9d69-44f2-95b6-4aa7e4bf630b">

2023-10-10 20:25 UTC, danielzeljko requested changes

2023-10-10 20:25 UTC, danielzeljko commented on langcorrect/templates/posts/partials/card_header.html
> +             alt="{{ user.nick_name|default_if_none:user.username }}'s avatar" />
We need to approach this differently (I've made this mistake as well in the old codebase). What we have right now is not DRY, and we'd have to remember to include this logic whenever we want to display the name across templates, which is prone to error.

What we should do instead is define a model property in the `User` model. This would make the code more maintainable and eliminate the need for repeated logic which will make this DRY. 

Here's how it would look like:


    @property
    def display_name(self):
       return self.nick_name if self.nick_name else self.username
 
 Then, in any template, you can access this via `{{ user.display_name }}` or in python code (ie: views, other methods like in the _build_avatar_url) via `user.display_name`.

https://docs.djangoproject.com/en/3.2/topics/db/models/#model-methods

2023-10-11 18:45 UTC, keyxcode commented
Besides the main points of this PR, I've also made one small change to the title of this page. I thought `User: {username}` didn't look quite right so I changed it to `My Profile`, which I thought went well with the other personal pages: `My Journals`, `My Prompts`. Please lmk what you think.
Other options that I considered: `{username}'s page` or simply `{username}`

2023-10-11 21:43 UTC, danielzeljko requested changes
I'm reviewing this on my phone while I have some downtime until my flight. Everything checks out with a quick glance. I'll need to run this on my local machine before approving it. I'll be able to get to this 2 days from now.

2023-10-11 21:43 UTC, danielzeljko commented on langcorrect/templates/users/user_detail.html
> +  My Profile
Let's expand on your idea so that if a user is viewing their own profile it'll show My Profile otherwise it'll show {user}'s profile. Nice idea!

2023-10-18 02:57 UTC, danielzeljko approved these changes

2023-10-18 03:04 UTC, danielzeljko approved these changes

2023-10-18 03:04 UTC, merged