Add background colors to corrections
LangCorrect/server pull request #244
Opened 2023-10-20 11:24 UTC by keyxcode

closes #205 

- I decided to make the text color for perfect sentences black (primary) because I thought it's easier to look at on green background.
- One thing I'm unsure about is the muted text for extra comments. I think it looks fine for short comments, but a bit hard to follow for longer ones. Let me know what you think.

2023-10-24 01:33 UTC, danielzeljko requested changes

2023-10-24 01:33 UTC, danielzeljko commented on langcorrect/templates/corrections/partials/correction.html
> +<div class="p-3 {% if correction.type == 'perfect' %} bg-success bg-opacity-25 {% else %} bg-warning bg-opacity-25 {% endif %}">
I feel that the yellow background is quite overwhelming, especially when they're placed consecutively next to each other. It tends to draw too much attention away. I'm not sure what colors would work in this context, but after playing around for a little bit, I managed to come up with this:

![image](https://github.com/LangCorrect/server/assets/115326106/2f092a34-a6ca-4281-8b22-530f788e6c9f)

If this version still feels harsh on the eyes, we could consider using a creamy or greyish color to compliment the green background without drawing too much attention away. I'm curious about which colors would achieve this balance, This would probably be better to discuss in a call so there's less back-and-forth communication on here.

2023-10-24 01:38 UTC, danielzeljko commented
> One thing I'm unsure about is the muted text for extra comments. I think it looks fine for short comments, but a bit hard to follow for longer ones. Let me know what you think @danielzeljko

I felt the same way, so I attempted to address this in the screenshot above. What I did was remove the `text-secondary` and added `bg-secondary bg-opacity-10` instead.

2023-10-29 14:15 UTC, keyxcode commented
Thanks for the feedback @danielzeljko
So after going through your suggestions, I've kinda synthesized them with my own ideas and come up with this version with the following changes:
- Removed the space around corrections and instead used a border for separation. I opted for the default border instead of a white border.
- Used `bg-light` for sentences that need correction. As for the extra comments, I decided to use the light yellow bg there instead of grey as you suggested. To me grey with green and white look a bit too cold and metalli while yellow adds a nice warm accentuation -- and it's also reminiscent of the original design. 

Pls lmk what you think!

<img width="879" alt="image" src="https://github.com/LangCorrect/server/assets/102985900/761aa639-7a8e-4574-b2bd-7f116f27968c">

2023-10-30 19:13 UTC, danielzeljko commented
@keyxcode 

Your changes look great! 💯 I don't know why I seem to have an affinity to post-apocalyptic LC 🤣

2023-11-01 04:02 UTC, danielzeljko requested changes

2023-11-01 04:02 UTC, danielzeljko commented on langcorrect/templates/corrections/partials/user_correction_card.html
> +  <div class="d-grids">
There's a typo here -- it should be `d-grid`, but I think we can most likely leave this out completely

2023-11-02 22:57 UTC, danielzeljko approved these changes

2023-11-02 22:57 UTC, merged