267 popular correctors design (wip)
LangCorrect/server pull request #296
Opened 2023-11-04 18:36 UTC by keyxcode

closes #267 

There are quite a few updates in this one so I thought it'd be a good idea to have you reviewed the current wip before I continue.

The most notable ones are:
- Added `display_name` to the qs that `get_popular_correctors` returns
- Modularized correctors list
- Got rid of the default Bootstrap tab button border and added underline for active tab via js

2023-11-07 01:33 UTC, danielzeljko requested changes
Looks good!

2023-11-07 01:33 UTC, danielzeljko commented on langcorrect/static/js/popular_correctors.js
I would look into overriding SASS variables here. This way even if someone has JS disabled in their browser, all of the designs will be uniformed across environments.

2023-11-07 01:33 UTC, danielzeljko commented on langcorrect/templates/corrections/partials/popular_corrector.html
> +    <span>{{ count }}.</span>
Count is implying some aggregation, but we're only using the loop counter here. I think it would be better to rename this to `idx`.

2023-11-07 05:09 UTC, keyxcode commented on langcorrect/static/js/popular_correctors.js
I actually never worked with SASS before. Would this be a good starting point? https://getbootstrap.com/docs/5.3/customize/sass/#:~:text=%3E-,Variable%20defaults,and%20remove%20the%20!default%20flag.

2023-11-12 02:47 UTC, keyxcode commented
I ended up overriding the stylings related to `nav-tabs` and `nav-link` in `project.scss`. Please lmk if this is the right approach!

2023-12-01 12:39 UTC, merged