Use display_name instead of username
LangCorrect/server pull request #339
Opened 2023-12-26 19:50 UTC by Raithlin

All relevant UI data points have been changed to use `display_name`.

A subsequent PR should correct the `display_name` function to use first/last name - or allow the user to modify `nickname`.

2023-12-26 21:33 UTC, danielzeljko requested changes

2023-12-26 21:33 UTC, danielzeljko commented on langcorrect/templates/emails/new_correction.html
> +        <h2>Hi, {{ display_name }}</h2>
We have a bug here where `display_name` will not evaluate to anything. We will need to update `email_new_correction()` to pass the `display_name` via context. See: https://github.com/LangCorrect/server/blob/7958fefd78e4f6158117272866dc52fe626a2fde/langcorrect/utils/mailing.py#L64

One approach could be to rename the `username` key to `user` and make sure we are accessing the `display_name` property instead of `username`, and then update the template variable.

2023-12-28 12:52 UTC, Raithlin commented on langcorrect/templates/emails/new_correction.html
> +        <h2>Hi, {{ display_name }}</h2>
Oops, my bad. I see how it works - I should have known better than to mess with template variables. Corrected and submitted, thanks.
I have kept the variable name as `username` for simplicity. It doesn't make sense to change the template variable to display_name. Ideally I thought `name` - but that is too common a keyword, whereas `username` defines the purpose perfectly.

2023-12-28 13:02 UTC, Raithlin commented on langcorrect/templates/emails/new_correction.html
> +        <h2>Hi, {{ display_name }}</h2>
Which tests did I not run to pick this up, out of interest? I ran the complete test suite but didn't do the optional extras mentioned on the readme.

2023-12-29 11:13 UTC, danielzeljko commented on langcorrect/templates/emails/new_correction.html
> +        <h2>Hi, {{ display_name }}</h2>
The project is lacking tests, so this would not have been picked up automatically. I think the overall coverage was like 30% or something like that.

2023-12-29 11:15 UTC, danielzeljko approved these changes

2023-12-29 11:16 UTC, danielzeljko commented
Looks good to me! Grats on your first PR 🎆

2023-12-29 11:19 UTC, merged