redirecting to feed after login
LangCorrect/server pull request #393
Opened 2024-01-06 18:04 UTC by jimkalis16

changed it so it redirects you to feed after login i couldn't test but its seems like it would work just fine if i did :) feel free to edit or ask me to do it if anything is wrong :)

2024-01-06 18:57 UTC, keyxcode commented
Hi and thanks @jimkalis16 !

What you wrote looks very logical but unfortunately it's not working here for me because there's neither a `journals` namespace nor a `redirect` path. There's a `home` path though and I think we could use it for this @danielzeljko

2024-01-06 19:33 UTC, danielzeljko requested changes

2024-01-06 19:33 UTC, danielzeljko commented on config/settings/base.py
> +LOGIN_REDIRECT_URL = "journals:redirect"
This should be:

    LOGIN_REDIRECT_URL = "posts:list"

2024-01-06 19:37 UTC, danielzeljko commented
So that home path would work because that view is checking if the user is logged in and redirecting to the correct place. I think in this case it would be better to take the user directly to the posts list: `posts:list`

2024-01-06 20:51 UTC, jimkalis16 commented on config/settings/base.py
> +LOGIN_REDIRECT_URL = "journals:redirect"
thanks for the help :)

2024-01-07 15:12 UTC, danielzeljko approved these changes

2024-01-07 15:39 UTC, merged