402 notifications page
LangCorrect/server pull request #441
Opened 2024-01-22 18:09 UTC by keyxcode

closes #402

2024-01-26 13:09 UTC, danielzeljko requested changes
One small change needed, but nicely done!

2024-01-26 13:09 UTC, danielzeljko commented on langcorrect/templates/notifications/partials/notification_loop.html
> +{% for notification in notifications %}
We should make the parent do the actual looping and keep the child to just render itself. This keeps the child component atomic allowing us to render this component anywhere within the app without any unwanted side effects. 

Parent

```
<div class="list-group list-group-flush mb-3">
   forloop
      include this template
      ....
   endfor
</div>
```

Let's rename the file from notification_loop.html to notification.html

2024-01-26 17:44 UTC, keyxcode commented on langcorrect/templates/notifications/partials/notification_loop.html
> +{% for notification in notifications %}
Great suggestion! Let me work on it.

2024-01-27 11:57 UTC, danielzeljko approved these changes
Looks good!

2024-01-27 11:57 UTC, merged